# Fly.io configuration for Seed Portal backend
# NOTE: Update the `app` name to your unique Fly app name (e.g., seed-portal-api-<org>)
app = "seed-portal-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

  [[http_service.checks]]
    interval = "10s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/api/healthz"
    protocol = "http"
