#!/bin/bash

# Setup script for Google Admin API ADC configuration

echo "=== Google Admin API Setup Instructions ==="
echo ""
echo "The current ADC file has an invalid refresh token that doesn't match your Google Console client."
echo ""
echo "To fix this, follow these steps:"
echo ""
echo "1. ON YOUR LOCAL MACHINE (not in Replit), run:"
echo ""
echo "   gcloud auth application-default login \\"
echo "     --scopes=https://www.googleapis.com/auth/admin.directory.user.readonly,https://www.googleapis.com/auth/admin.directory.group.readonly"
echo ""
echo "2. This will open a browser - sign in with your @seedfinancial.io admin account"
echo ""
echo "3. Find the generated ADC file on your local machine:"
echo "   - Mac/Linux: ~/.config/gcloud/application_default_credentials.json"
echo "   - Windows: %APPDATA%\\gcloud\\application_default_credentials.json"
echo ""
echo "4. Copy the ENTIRE contents of that file"
echo ""
echo "5. In Replit, run:"
echo "   mkdir -p ~/.config/gcloud"
echo "   nano ~/.config/gcloud/application_default_credentials.json"
echo ""
echo "6. Paste the contents, save (Ctrl+O, Enter, Ctrl+X)"
echo ""
echo "7. Restart the application"
echo ""
echo "IMPORTANT: Do NOT set GOOGLE_APPLICATION_CREDENTIALS environment variable"
echo ""
echo "The ADC file will be auto-discovered at ~/.config/gcloud/application_default_credentials.json"